### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'aiosession'

### ISSUE THREAD

**Issue by simon-ne** [ajndkr/lanarky#148]
### Problem
Im returning `StreamingResponse.from_chain(chain, inputs, media_type="text/event-stream")`.
With openai python package version 0.28.1 everything works fine, but after updating to 1.2.4 this call causes an exception:
`AttributeError: module 'openai' has no attribute 'aiosession'`.

### Cause
In the [migration guide](https://github.com/openai/openai-python/discussions/742) you can see that the openai.aiosession has been removed in openai 1.0.0 and higher.

**Comment by ajndkr** [comment]
@simon-ne is `openai>1.0.0` mandatory for you? I will add support for it in v0.8

**Comment by Krupskis** [comment]
@ajndkr Let me know if I can help with the migration

**Comment by ajndkr** [comment]
Feel free to open a PR if you have a fix ready but since this is a breaking dependency change, i want to push it with v0.8

**Comment by ajndkr** [comment]
@simon-ne @Krupskis i've bumped openai dependency in #149 but the changes will come into effect with v0.8 release. i have other features/bugfixes in mind. Will take a week or so until i make the new release.
